### ISSUE TITLE
HTML tags in metadata description

### ISSUE THREAD

**Issue by Prilann** [sachaw/AniList.bundle#1]
Hi, not a real issue more like a wish.
In the descriptions of the tv shows, I often have HTML tags like "<br>".
Is it possible that you can filter these? 
As I mentioned its not an issue but it would look nicer.
Would be awesome.

Thank you

**Comment by sachaw** [comment]
I'll have a look into it today

**Comment by sachaw** [comment]
Fixed https://github.com/sachaw/AniList.bundle/commit/9811e9f8a5c7b3ad22dae6cbf16b9bd064f90c04
