### ISSUE TITLE
Multiple seasons?

### ISSUE THREAD

**Issue by Soitora** [sachaw/AniList.bundle#2]
How does this work for multiple seasons? I tried it on one anime entry and it kept the same cover both both seasons unfortunately

**Comment by halomademeapc** [comment]
A lot of anime are set up like sequels instead of seasons. I like to treat them as separate shows and then group them together with a collection in Plex myself. This works especially well for series like monogatari that don't follow a serial naming pattern and don't fit well with a numbered series structure

**Comment by Soitora** [comment]
This is why I didn't use AniDB :/
Either way good luck with the bundle then and I'll keep using TheTVDB until something similiar comes out :)

**Comment by sachaw** [comment]
@Soitora can you give me an example, I may be able to implement auto collection support.

**Comment by Soitora** [comment]
> @Soitora can you give me an example, I may be able to implement auto collection support.

Example of what? An anime? Or another agent that does this?

**Comment by sachaw** [comment]
An anime that you want to group seasons of

**Comment by Soitora** [comment]
Okay so an example here with parts could be Re:Zero.

Season 1: https://anilist.co/anime/21355/ReZero-kara-Hajimeru-Isekai-Seikatsu/
Season 2 Part 1: https://anilist.co/anime/108632/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season/
Season 2 Part 2: https://anilist.co/anime/119661/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season-Part-2/

**Comment by Pure-Disgust** [comment]
Any progress on this? Really like the agent, but it not recognizing multiple seasons is a bit of a deal breaker for me

**Comment by sachaw** [comment]
I could look at implementing this,
If anyone could define the constrains of classifying seasons, based on what data is available in the api (this is the difficult part) I could work on this.

**Comment by halomademeapc** [comment]
If you do implement this can you make it toggleable in the settings? One of the main reasons I use this bundle is that it _doesn't_ try to organize things into seasons. The agents that do that typically make a mess out of shows like Monogatari or Lupin III that aren't organized into bespoke numbered seasons.

**Comment by sachaw** [comment]
@halomademeapc certainly, if it is implemented it will be off by default as anilist has flat libraries anyway (each season is it's own show)
