### ISSUE TITLE
Metadata Sources Question

### ISSUE THREAD

**Issue by ilikpoptarts** [sachaw/AniList.bundle#7]
Hi, I was wondering what sources does this pull media? What kind of metadata does it pull? Is it just AniList? Is it able to grab much in the way of pictures and backgrounds from AniList? (if it grabs them from AniList at all)
Sorry if this is stated somewhere as I could not find much information on this project.

I'm stupid and don't know how to label this as "question". (If I can)

**Comment by sachaw** [comment]
Hi, this agent uses the Anilist GraphQL API, exactly the same as the website does, currently it pulls the following data:
https://github.com/sachaw/AniList.bundle/blob/46c20a912bac7321205bf873b7150095393c4d8a/Contents/Code/providers.py#L10-L92
And also episode titles from MyAnimeList. (This can be disabled in the settings)

If there is any other data you want me to fetch, please let me know.

**Comment by sachaw** [comment]
An example of a movie with this agent
![screencapture-app-plex-tv-desktop-2022-01-02-19_05_38-min](https://user-images.githubusercontent.com/11172820/147869927-f86b8cf3-676e-4c12-8978-5ccbf90c3c86.png)
