### ISSUE TITLE
Plug-in not fetching metadata for episodes 101+

### ISSUE THREAD

**Issue by pilar6195** [sachaw/AniList.bundle#8]
Plug-in is not fetching the metadata for episodes 101+ for shows with over 100 episodes in a season. Example being Hunter X Hunter.

From the looks of it you are using Jikan to fetch the MAL data. They do pagination for this endpoint and will only return 100 results which will require additional requests to fetch the rest of the data. The plug-in does not seem to account for this. It is noted in the v3 docs which you can find [here](https://jikan.docs.apiary.io/#reference/0/anime) under the "Remarks" section.

Also on a side note, the v3 Jikan api is deprecated. Should probably also migrate to the v4 api.

I would open a PR but I'm not really familiar with python.

**Comment by sachaw** [comment]
Thanks for the investigating 🔎

I'll take a look at this tonight and hopefully push a fix.

**Comment by sachaw** [comment]
@pilar6195 https://github.com/sachaw/AniList.bundle/commit/4a4f313e5de7e00624bb455a5ccaa7408e6ff4b7 is now in, Please try out https://github.com/sachaw/AniList.bundle/releases/tag/2.9
This should have addressed all of your points.

Please keep an eye out for any series not behaving as expected, Thanks.
