### ISSUE TITLE
Agent only appears under Movies Agents for 2.9

### ISSUE THREAD

**Issue by Morutimeru** [sachaw/AniList.bundle#9]
Hello.

I'm trying to use this but I only see the Agent under Movies, not on Shows. Shouldn't it appear under Shows because that's what ASS uses?

If you need any logs please tell me what logs do I need to get to you.

Thanks.

![image](https://user-images.githubusercontent.com/10160055/160491494-b293cf0f-dbdc-424f-91e9-56dfd0149b30.png)

![image](https://user-images.githubusercontent.com/10160055/160491519-67859492-7e26-4f83-bf88-7f43a6f8e6bd.png)

**Comment by sachaw** [comment]
I'll take a look at this a bit later today, please confirm you have the latest version.

Stop the server, delete and re-add the agent, start plex

**Comment by Morutimeru** [comment]
Yeah, this is 2.9, the latest, just redid the process again and got the same results.
This a docker container  with docker volumes, so I stopped the plex container, mounted the volume on another container, got the tarball from git and put it on the Plug-ins folder.

![image](https://user-images.githubusercontent.com/10160055/160498706-ded98577-83f8-4044-8607-8e2c97554390.png)

**Comment by sachaw** [comment]
Just some basic troubleshooting, can you please ensure you are running the latest Plex version (shouldn't matter), I'm running `1.25.8.5663`.

Also, please try using https://app.plex.tv to access your server.

Lastly, even if it's not listed under `Series`>`Agents`, see if you can set it as the agent for a tv library.

**Comment by sachaw** [comment]
Another thing to try would be to remove `System.bundle` and `Framework.bundle` from the installation folder, Plex will regenerate them when it restarts.

**Comment by Morutimeru** [comment]
Thanks sachaw, tried all of that and now it's working. Got a question, since now there's an agent for anilist on movies, with what scanner do we use that? ASS does not show in movies because it is a series only scanner I think.

**Comment by sachaw** [comment]
Great to hear, ASS is used for the episode naming convention and won't merge things together like the Plex one does. As movies are usually just a single file, the default Plex movie scanner works fine.

**Comment by Morutimeru** [comment]
Great, thanks for your answers @sachaw , will close this.
